const RECEIVE_QUESTIONS = "RECEIVE_QUESTIONS";
const ANSWER_QUESTION = "ANSWER_QUESTION";
const ADD_QUESTION = "ADD_QUESTION";

const SET_AUTHED_USER = "SET_AUTHED_USER";

const RECEIVE_USERS = "RECEIVE_USERS";
const ADD_USER_ANSWER = "ADD_USER_ANSWER";
const ADD_USER_QUESTION = "ADD_USER_QUESTION";

export {
	RECEIVE_QUESTIONS,
	ANSWER_QUESTION,
	ADD_QUESTION,
	SET_AUTHED_USER,
	RECEIVE_USERS,
	ADD_USER_ANSWER,
	ADD_USER_QUESTION
}